# Generated by Django 5.2.6 on 2025-09-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Користувач'), ('moderator', 'Модератор'), ('admin', 'Адміністратор')], default='user', max_length=20),
        ),
    ]
