# Generated by Django 5.2.6 on 2025-10-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='Назва групи')),
                ('curator', models.CharField(max_length=200, verbose_name='Куратор')),
                ('student_count', models.PositiveIntegerField(verbose_name='Кількість студентів')),
                ('description', models.TextField(blank=True, verbose_name='Опис групи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Інформація про групу',
                'verbose_name_plural': 'Інформація про групи',
            },
        ),
    ]
