# Generated by Django 5.2.6 on 2025-10-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinfo',
            name='description',
        ),
    ]
